### ISSUE TITLE
Import csv data option.

### ISSUE THREAD

**Issue by vipuldamani** [ostigter/portfolio-manager#4]
Good Morning Sir,
can you add option like *.csv or excel import option , so no human error possible.
Please send me new release download link also.

**Comment by ostigter** [comment]
Hi vipuldamani,

Thank you for your interest in my Portfolio Manager application!

As a very passionate investor I use it every day, but I've stopped active development on it, as it already does everything I currently need (watch my current positions, interesting stocks, dividend income, net total return and all-time CAGR). I simply don't have the motivation and energy. There are many features that the application could be extended with. (Unfortunately, some features described on the main page aren't even present anymore due to changes in third-party data APIs.)

If you take a look at the 'transactions' array in the data file (JSON; add some test Buy/Sell/Dividend transactions manually first), I'm sure you can create a tool yourself that converts a CSV file to that JSON format and you can simply insert it in the data file.

Regards,
Oscar
